pipeline {
    agent {
        label 'ansible'
    }

    stages {
        stage('git') {
            steps {
                git branch: 'master', credentialsId: 'caevert_github', url: 'https://github.com/caevert/mnt-homeworks/blob/master/09-ci-04-jenkins/assets'
            }
        }
        stage('Molecule test in docker') {
            steps {
                sh 'molecule test -s docker'
            }
        }
    }
}
